language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: stable
      os: osx
    - rust: stable
      env: FEATURES="--features serde"
    - rust: nightly
      env: FEATURES="--features nightly"

script: ./travis.sh
