environment:
  matrix:
    # Minimum version
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "1.20.0"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "1.20.0"
    # Stable channel
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "stable"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "stable"
    # Beta channel
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "beta"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "beta"
    # Nightly channel
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "nightly"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "nightly"

branches:
  only:
    - master

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# `cargo test` takes care of this
build: false

test_script:
  - cargo test -p hexe      $FEATURES
  - cargo test -p hexe_core $FEATURES
  - cargo test -p hexe_core $FEATURES --no-default-features
