[package]
name = "hexe_core"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/hexe-rs/Hexe"
categories = ["no-std"]
description = "The core components of the hexe chess engine crate."
include = ["Cargo.toml", "src/**/*.rs", "README*", "CHANGELOG*", "LICENSE*"]

[badges]
travis-ci = { repository = "hexe-rs/Hexe" }

[dependencies]
serde        = { version = "1.0",   default-features = false, optional = true }
uncon        = { version = "1.1.0", default-features = false }
uncon_derive = { version = "1.1.0", default-features = false }

[dev-dependencies]
rand = "0.3"

[features]
default = ["std"]
nightly = ["try-from"]
std = ["uncon/std", "uncon_derive/std"]
try-from = []
