[package]
name = "hexe_bin"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/hexe-rs/Hexe"
description = "A chess engine."
documentation = "https://docs.rs/hexe_bin"
include = ["Cargo.toml", "src/**/*.rs", "README*", "CHANGELOG*", "LICENSE*"]

[[bin]]
name = "hexe"
path = "src/main.rs"

[dependencies]
hexe = { path = "../hexe", version = "0.0.0" }

[features]
simd = ["hexe/simd",  "hexe_core/simd"]
