[package]
name = "hexe"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "Apache-2.0"
description = "A chess engine."

[dependencies]
hexe_core = { path = "../hexe_core", version = "0.0.0" }
