[package]
name = "hexe"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "Apache-2.0"
repository = "https://github.com/hexe-rs/Hexe"
description = "A chess engine."
include = ["Cargo.toml", "src/**/*.rs", "README*", "CHANGELOG*", "LICENSE*"]

[badges]
travis-ci = { repository = "hexe-rs/Hexe" }

[dependencies]
hexe_core = { path = "../hexe_core", version = "0.0.0" }

[features]
nightly = ["hexe_core/nightly", "try-from"]
try-from = ["hexe_core/try-from"]
serde = ["hexe_core/serde"]
