[package]
name = "hexe"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/hexe-rs/Hexe"
description = "A chess engine."
documentation = "https://docs.rs/hexe"
include = ["Cargo.toml", "src/**/*.rs", "README*", "CHANGELOG*", "LICENSE*"]

[badges]
travis-ci = { repository = "hexe-rs/Hexe" }

[dependencies]
hexe_core    = { path = "../hexe_core", version = "0.0.0" }
uncon        = { version = "1.1.0" }
uncon_derive = { version = "1.1.1" }

[dev-dependencies]
static_assertions = "0.2"

[features]
serde = ["hexe_core/serde"]
simd = ["hexe_core/simd"]
