[package]
name = "hexe"
version = "0.0.0"
authors = ["Nikolai Vazquez"]
license = "Apache-2.0"
repository = "https://github.com/hexe-rs/Hexe"
description = "A chess engine."
include = ["Cargo.toml", "src/**/*.rs", "README*", "CHANGELOG*", "LICENSE*"]

[dependencies]
hexe_core = { path = "../hexe_core", version = "0.0.0" }
